### PR TITLE
Update SSC

### PR DESCRIPTION
**Pull request by jerluc**
This changeset updates sscpy to take advantage of newer versions of the SSC native library:

- Updates to the Docker image to incorporate the latest [ssc-docker](https://github.com/StationA/ssc-docker) changes
- Renames the `PVWattsV5` API to `PVWatts` (with an optional constructor arg for choosing the variable)
- Moves the `sscapi.h` file out of the `ffibuilder.py` code to make future SSC upgrades simpler
- Code-style updates to use our standard `black` conventions

### CODE REVIEW

**Review by manossaratsis — APPROVED** [review]
🏁 🌞

**Review by ccma14 — COMMENTED** [review]
One thing I don't grok is that we seem to have two copies of `sscapi.h`: One that gets copied over via `Dockerfile` and one that is checked in via `ssc/sscapi.h`.

I'd argue ideally we want ffi to use the one that gets copied over in the `Dockerfile` because we know that this one is consistent with the library, that also gets copied over, hence I'd say we should probably not have the checked in version.

Or am I missing something here?

**Comment by ccma14** [comment]
> Or am I missing something here?

I guess the two `sscapi.h` files are different? The checked-in one is the dumbed-down version for `ffi`, containing what was previously embedded in the ffi .py file?

**Comment by jerluc** [comment]
> > Or am I missing something here?
> 
> I guess the two `sscapi.h` files are different? The checked-in one is the dumbed-down version for `ffi`, containing what was previously embedded in the ffi .py file?

@ccma14 yeah the difference is that the checked-in one is for the Python package (which should reflect the latest header used to compile the native library). Honestly the header file copied in from the pre-built Docker image isn't necessary, but is just "good hygiene" IMO. Maybe it's possible to filter out all of the non-cffi stuff automatically, but I'm not aware of how that can be done.

**Pull request merged**
